### ISSUE TITLE
when i run the project just showing app state?? and kindly tell how to run backend of that project

### ISSUE THREAD

**Issue by abdullah8sheikh** [lmanukyan/print-designer#3]
![image](https://github.com/lmanukyan/print-designer/assets/113443843/0605d12c-e41c-46a1-9c45-cfb85506cd92)

**Comment by abdullah8sheikh** [comment]
![image](https://github.com/lmanukyan/print-designer/assets/113443843/324cf02d-c275-4c43-ae8b-2deefea41acd)

**Comment by lmanukyan** [comment]
Does the project folder name contain spaces or parentheses?

https://stackoverflow.com/questions/71413575/vue-js-error-in-conflict-multiple-assets-emit-different-content-to-the-same-f

**Comment by abdullah8sheikh** [comment]
that index.html conflicts problem sorted but still showing me that page 

![326042775-0605d12c-e41c-46a1-9c45-cfb85506cd92](https://github.com/lmanukyan/print-designer/assets/113443843/f3359bac-abec-41ff-b4be-bab786da2c2a)


and kindly tell me how can i run backend of that project???

**Comment by lmanukyan** [comment]
yarn dev

**Comment by abdullah8sheikh** [comment]
[image: image.png]
showing me this error

**Comment by lmanukyan** [comment]
The screenshot does not open. Please resend it.

![IMG_20240428_235653](https://github.com/lmanukyan/print-designer/assets/53080789/5e700750-44c7-44ff-ad51-d6bce7539051)

**Comment by abdullah8sheikh** [comment]
![c2314d9b-c13f-43eb-8f18-a36710a14098](https://github.com/lmanukyan/print-designer/assets/113443843/f3ce2dfc-a81d-40b5-b4a7-6d60e0ccdcaf)

now my backend is running properly but in front end still showing that page

**Comment by lmanukyan** [comment]
Open the admin panel and add at least one product.
